#!/usr/bin/env bash
# Logging + quirk capture library
# Source this from other scripts: source "$SCRIPT_DIR/lib/log.sh"

# Colors
if [[ -t 1 ]]; then
  C_RESET=$'\033[0m'
  C_BOLD=$'\033[1m'
  C_DIM=$'\033[2m'
  C_RED=$'\033[31m'
  C_GREEN=$'\033[32m'
  C_YELLOW=$'\033[33m'
  C_MAGENTA=$'\033[35m'
  C_CYAN=$'\033[36m'
else
  C_RESET='' C_BOLD='' C_DIM='' C_RED='' C_GREEN='' C_YELLOW='' C_MAGENTA='' C_CYAN=''
fi

# Stage / step names for the orchestrator
STAGE_NAME="${STAGE_NAME:-run}"
STEP_NUM="${STEP_NUM:-0}"
QUIRK_COUNT=0
FAIL_COUNT=0
PASS_COUNT=0
SKIP_COUNT=0

# Set QUIRK_LOG via env or default to <workspace>/QUIRKS.md
WORKSPACE_ROOT="${WORKSPACE_ROOT:-/home/luandro/Dev/coolab/colmena}"
QUIRK_LOG="${QUIRK_LOG:-$WORKSPACE_ROOT/QUIRKS.md}"

_log() { printf '%s\n' "$*"; }
_err() { printf '%s\n' "$*" >&2; }

# timestamp
ts() { date '+%Y-%m-%dT%H:%M:%S%z'; }

# stage banner
stage() {
  local n="$1"; shift
  local name="$1"; shift
  printf '\n%s%s[%02d] %s%s\n' "$C_BOLD$C_CYAN" "$STAGE_NAME" "$n" "$name" "$C_RESET"
  printf '%s%s%s\n' "$C_DIM" "$(printf -- '-%.0s' {1..60})" "$C_RESET"
  _log "  stage=$STAGE_NAME step=$n name=$name ts=$(ts)"
}

step() { printf '  %s•%s %s\n' "$C_DIM" "$C_RESET" "$*"; }

ok()   { printf '  %s✓%s %s\n' "$C_GREEN" "$C_RESET" "$*"; PASS_COUNT=$((PASS_COUNT+1)); }
fail() { printf '  %s✗%s %s\n' "$C_RED" "$C_RESET" "$*"; FAIL_COUNT=$((FAIL_COUNT+1)); }
warn() { printf '  %s!%s %s\n' "$C_YELLOW" "$C_RESET" "$*"; }
skip() { printf '  %s-%s %s\n' "$C_DIM" "$C_RESET" "$*"; SKIP_COUNT=$((SKIP_COUNT+1)); }
info() { printf '    %s\n' "$*"; }

# quirk: capture a non-fatal oddity for later review
quirk() {
  local title="$1"; shift
  local detail="$1"; shift || true
  ((QUIRK_COUNT++))
  printf '  %s?%s %s%s%s\n' "$C_MAGENTA" "$C_RESET" "$C_BOLD" "$title" "$C_RESET"
  [[ -n "$detail" ]] && info "$detail"
  _append_quirk "$title" "$detail"
}

_append_quirk() {
  local title="$1" detail="$2"
  {
    printf -- "- \`%s\` **%s** — %s\n" "$(ts)" "$title" "${detail:-no detail}"
  } >> "$QUIRK_LOG"
}

reset_quirk_log() {
  : > "$QUIRK_LOG"
  {
    printf '# Quirks log\n\n'
    printf "Auto-generated by \`run-stack.sh\`. Each line is one non-fatal oddity encountered during a stack run.\n\n"
    printf 'Run started: %s\n\n' "$(ts)"
  } > "$QUIRK_LOG"
}

finalize_quirk_log() {
  local stage_pass="${1:-}"
  local stage_fail="${2:-}"
  local quirk_total
  quirk_total=$(grep -c '^- `' "$QUIRK_LOG" 2>/dev/null || true)
  {
    printf -- '\n## Summary\n\n'
    if [[ -n "$stage_pass" && -n "$stage_fail" ]]; then
      printf -- '- stages passed: %d\n' "$stage_pass"
      printf -- '- stages failed: %d\n' "$stage_fail"
    fi
    printf -- '- quirks: %d\n' "$quirk_total"
    printf -- '- finished: %s\n' "$(ts)"
  } >> "$QUIRK_LOG"
}

# Run a command, log success/failure, and capture stderr to a log file
run() {
  local desc="$1"; shift
  local logf="$1"; shift
  if "$@" >>"$logf" 2>&1; then
    ok "$desc"
    return 0
  else
    local rc=$?
    fail "$desc (exit=$rc; see $logf)"
    return $rc
  fi
}

# Run a command, capture output to log, but never fail
try() {
  local desc="$1"; shift
  local logf="$1"; shift
  if "$@" >>"$logf" 2>&1; then
    ok "$desc"
    return 0
  else
    local rc=$?
    warn "$desc (exit=$rc; see $logf)"
    echo "$rc" > "$WORKSPACE_ROOT/.last_try_rc"
    return $rc
  fi
}

# Print final summary
summary() {
  printf '\n%s%sSummary%s\n' "$C_BOLD" "$C_CYAN" "$C_RESET"
  printf '  pass:   %s%d%s\n' "$C_GREEN" "$PASS_COUNT" "$C_RESET"
  printf '  fail:   %s%d%s\n' "$C_RED" "$FAIL_COUNT" "$C_RESET"
  printf '  skip:   %s%d%s\n' "$C_DIM" "$SKIP_COUNT" "$C_RESET"
  printf '  quirks: %s%d%s (see %s)\n' "$C_MAGENTA" "$QUIRK_COUNT" "$C_RESET" "$QUIRK_LOG"
  # Always return success so the orchestrator's set -e doesn't trip on this
  return 0
}

finish_stage() {
  summary
  [[ "$FAIL_COUNT" -eq 0 ]]
}
